In [3]:
#one hot encoding coverts categorical data into numerical values which represent each category. but its disadvantage is that
# it creates many new columns if there are many features for a single category.
# like colour category has many features like different colours. 
# the matrix that will be created when features are converted into numerical values is caled sparse matrix.
# like when data is seen of 0,0,1 like of three columns together it will be like a matrix so that matrix like looking is called sparse matrix

In [2]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
#create a colour category with multiple features(shades)
df=pd.DataFrame({
    'colours':['red','green','yellow','red','blue','green']
})

In [ ]:
#create an instance for the one hot encoder
# than we fit and transform
encoder=OneHotEncoder()

In [5]:
df

  colours
0     red
1   green
2  yellow
3     red
4    blue
5   green

In [10]:
encoded=encoder.fit_transform(df[['colours']]).toarray() # gives you the sparse matrix the matrix that shows numerical values.

In [11]:
# convert it in dataframe
encoded_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [12]:
encoded_df

   colours_blue  colours_green  colours_red  colours_yellow
0           0.0            0.0          1.0             0.0
1           0.0            1.0          0.0             0.0
2           0.0            0.0          0.0             1.0
3           0.0            0.0          1.0             0.0
4           1.0            0.0          0.0             0.0
5           0.0            1.0          0.0             0.0

In [ ]:
pd.concat([df,encoded_df],axis=1) # as you can see the category numerical values are ready that can be shared with the model.

  colours  colours_blue  colours_green  colours_red  colours_yellow
0     red           0.0            0.0          1.0             0.0
1   green           0.0            1.0          0.0             0.0
2  yellow           0.0            0.0          0.0             1.0
3     red           0.0            0.0          1.0             0.0
4    blue           1.0            0.0          0.0             0.0
5   green           0.0            1.0          0.0             0.0

In [17]:
# if you have new data.
encoder.transform([['blue']]).toarray()

e:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0., 0.]])

In [21]:
import seaborn as sns
data=sns.load_dataset('tips')

In [23]:
data#category like sex smker day time all categorys

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [28]:
encoder=OneHotEncoder(sparse_output=False)  # wrote this as onehotencoder gives wrong or multiple column names adding earlier one also so we clear it.
encoded=encoder.fit_transform(data[['sex','time','day']])

In [29]:
encoded_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [30]:
encoded_df

,sex_Female,sex_Male,time_Dinner,time_Lunch,day_Fri,day_Sat,day_Sun,day_Thur
0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
2,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
3,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
4,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...
239,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
240,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
241,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
242,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
243,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [34]:
pd.concat([data[['sex','day','time']],encoded_df],axis=1)

,sex,day,time,sex_Female,sex_Male,time_Dinner,time_Lunch,day_Fri,day_Sat,day_Sun,day_Thur
0,Female,Sun,Dinner,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,Male,Sun,Dinner,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
2,Male,Sun,Dinner,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
3,Male,Sun,Dinner,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
4,Female,Sun,Dinner,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
239,Male,Sat,Dinner,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
240,Female,Sat,Dinner,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
241,Male,Sat,Dinner,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
242,Male,Sat,Dinner,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
243,Female,Thur,Dinner,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [35]:
#label and ordinal encoding
# labeling means to label to the data and ordinal encoding means to rank those labels
# as it is possible that the machine learning model will understand by seeing that the repetition of an feature will be the large one. but we need to stop
# this by ranking.

In [36]:
from sklearn.preprocessing import LabelEncoder
df=pd.DataFrame({
    'colours':['red','green','yellow','red','blue','green']
})

In [38]:
encoder=LabelEncoder()

In [39]:
label=encoder.fit_transform(df[['colours']])

e:\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
label # as model will consider 3 label as the laargest but that can not be true. so to solve this we use odinal encoding which do ranking.

array([2, 1, 3, 2, 0, 1])

In [52]:
from sklearn.preprocessing import OrdinalEncoder
df=pd.DataFrame({
    'size':['small','medium','largest','medium','largest','largest']
})

encoder=OrdinalEncoder(categories=[['small','medium','largest']])

In [53]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [2.],
       [2.]])

In [54]:
#so now we have ranked the most repeated value so that ml model will understand which is the largest correctly.

In [55]:
#now we do target guided ordinal encoding
# create a sample dataframe with a categorical variable and a target variable
df = pd.DataFrame({
    'city': ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200, 150, 300, 250, 180, 320]  # it is a target variable as it defines the rate of each country.
})

In [57]:
mean=df.groupby('city')['price'].mean().to_dict()

In [60]:
import pandas as pd
df['city_encoded']=df['city'].map(mean)

In [63]:
df[['price','city_encoded']]

   price  city_encoded
0    200         190.0
1    150         150.0
2    300         310.0
3    250         250.0
4    180         190.0
5    320         310.0